# Generated by Django 6.0 on 2025-12-20 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-cube', help_text='مثال: fas fa-glasses', max_length=50, verbose_name='أيقونة')),
                ('color', models.CharField(default='#4A9EAD', help_text='مثال: #FF5733', max_length=7, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='كود المعمل')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم المعمل')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='يجب أن يبدأ رقم الجوال بـ 5 ويتكون من 9 أرقام', regex='^5\\d{8}$')], verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('representative_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المندوب')),
                ('representative_phone', models.CharField(blank=True, max_length=9, verbose_name='جوال المندوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'معمل',
                'verbose_name_plural': 'المعامل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='كود المورد')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='يجب أن يبدأ رقم الجوال بـ 5 ويتكون من 9 أرقام', regex='^5\\d{8}$')], verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('representative_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المندوب')),
                ('representative_phone', models.CharField(blank=True, max_length=9, verbose_name='جوال المندوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='الباركود')),
                ('sku', models.CharField(blank=True, help_text='رمز المنتج الداخلي', max_length=50, verbose_name='SKU')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('min_quantity', models.IntegerField(default=5, help_text='تنبيه عند الوصول لهذا الحد', verbose_name='الحد الأدنى للكمية')),
                ('box_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الصندوق')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.category', verbose_name='التصنيف')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'إدخال'), ('out', 'إخراج'), ('adjustment', 'تعديل'), ('return', 'مرتجع')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('previous_quantity', models.IntegerField(verbose_name='الكمية السابقة')),
                ('new_quantity', models.IntegerField(verbose_name='الكمية الجديدة')),
                ('reference', models.CharField(blank=True, help_text='مثال: رقم الفاتورة', max_length=100, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='stock_produ_barcode_3bf23c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_name'], name='stock_produ_item_na_199dd2_idx'),
        ),
    ]
