# Generated by Django 6.0 on 2025-12-20 22:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المجموعة')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='عرض التقارير')),
                ('can_manage_sales', models.BooleanField(default=False, verbose_name='إدارة المبيعات')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='إدارة المخزون')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='إدارة العملاء')),
                ('can_manage_suppliers', models.BooleanField(default=False, verbose_name='إدارة الموردين')),
                ('can_view_financial', models.BooleanField(default=False, verbose_name='عرض البيانات المالية')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='إدارة الإعدادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_group', to='auth.group')),
            ],
            options={
                'verbose_name': 'مجموعة موظفين',
                'verbose_name_plural': 'مجموعات الموظفين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('full_name_arabic', models.CharField(max_length=200, verbose_name='الاسم الكامل بالعربي')),
                ('position', models.CharField(choices=[('manager', 'مدير'), ('accountant', 'محاسب'), ('sales', 'موظف مبيعات'), ('inventory', 'أمين مخزن'), ('technician', 'فني'), ('cashier', 'كاشير'), ('other', 'أخرى')], max_length=50, verbose_name='المسمى الوظيفي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يبدأ بـ 05 ويتكون من 10 أرقام', regex='^05\\d{8}$')], verbose_name='رقم الجوال')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='رقم الهوية الوطنية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='صورة الموظف')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التوظيف')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الخدمة')),
                ('termination_reason', models.TextField(blank=True, verbose_name='سبب إنهاء الخدمة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['-created_at'],
                'permissions': [('view_salary', 'يمكنه عرض الرواتب'), ('manage_employees', 'يمكنه إدارة الموظفين')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='الوقت')),
                ('type', models.CharField(choices=[('in', 'حضور'), ('out', 'انصراف')], max_length=10, verbose_name='النوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='الإجراء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'نشاط موظف',
                'verbose_name_plural': 'نشاطات الموظفين',
                'ordering': ['-created_at'],
            },
        ),
    ]
