# Generated by Django 6.0 on 2025-12-14 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المرفق')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='الملف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ar', models.CharField(blank=True, max_length=200, verbose_name='اسم المؤسسة (عربي)')),
                ('company_name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم المؤسسة (إنجليزي)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='شعار المؤسسة')),
                ('unified_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الموحد')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('national_address', models.TextField(blank=True, verbose_name='العنوان الوطني')),
                ('location_url', models.URLField(blank=True, verbose_name='رابط الموقع')),
                ('contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بصيغة: '0501234567' أو '+966501234567'", regex='^\\+?966?\\d{9,10}$')], verbose_name='رقم الجوال')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المفوض/المالك')),
                ('owner_id_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('owner_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بصيغة: '0501234567' أو '+966501234567'", regex='^\\+?966?\\d{9,10}$')], verbose_name='رقم جوال المفوض')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد المفوض الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المؤسسة',
                'verbose_name_plural': 'إعدادات المؤسسة',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='الشركة')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='نسبة العمولة إن وجدت', max_digits=5, null=True, verbose_name='النسبة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['name'],
            },
        ),
    ]
