# Generated by Django 6.0 on 2025-12-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('daily_balance', 'الموازنة اليومية'), ('revenue', 'تقرير الإيرادات'), ('inventory', 'تقرير المخزون'), ('sales', 'تقرير المبيعات'), ('customers', 'تقرير العملاء'), ('products', 'تقرير المنتجات'), ('payments', 'تقرير المدفوعات'), ('profit', 'تقرير الأرباح')], max_length=50, verbose_name='نوع التقرير')),
                ('date_from', models.DateField(verbose_name='من تاريخ')),
                ('date_to', models.DateField(verbose_name='إلى تاريخ')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='البيانات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(max_length=100, verbose_name='أنشئ بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجدولة')),
                ('report_type', models.CharField(choices=[('daily_balance', 'الموازنة اليومية'), ('revenue', 'تقرير الإيرادات'), ('inventory', 'تقرير المخزون'), ('sales', 'تقرير المبيعات'), ('customers', 'تقرير العملاء'), ('products', 'تقرير المنتجات'), ('payments', 'تقرير المدفوعات'), ('profit', 'تقرير الأرباح')], max_length=50, verbose_name='نوع التقرير')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=20, verbose_name='التكرار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل القادم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'جدولة تقرير',
                'verbose_name_plural': 'جدولة التقارير',
                'ordering': ['-created_at'],
            },
        ),
    ]
