# Generated by Django 6.0 on 2025-12-14 13:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم العميل')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم الثلاثي')),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يبدأ رقم الجوال بـ 5 ويتكون من 9 أرقام', regex='^5\\d{8}$')], verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notify_whatsapp', models.BooleanField(default=True, verbose_name='إشعارات واتساب')),
                ('notify_sms', models.BooleanField(default=True, verbose_name='إشعارات SMS')),
                ('notify_email', models.BooleanField(default=False, verbose_name='إشعارات البريد')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفحص')),
                ('right_sphere', models.CharField(blank=True, max_length=10, verbose_name='القوة الكروية - يمنى')),
                ('right_cylinder', models.CharField(blank=True, max_length=10, verbose_name='القوة الأسطوانية - يمنى')),
                ('right_axis', models.CharField(blank=True, max_length=10, verbose_name='المحور - يمنى')),
                ('right_add', models.CharField(blank=True, max_length=10, verbose_name='القراءة - يمنى')),
                ('right_pd', models.CharField(blank=True, max_length=10, verbose_name='المسافة البؤرية - يمنى')),
                ('left_sphere', models.CharField(blank=True, max_length=10, verbose_name='القوة الكروية - يسرى')),
                ('left_cylinder', models.CharField(blank=True, max_length=10, verbose_name='القوة الأسطوانية - يسرى')),
                ('left_axis', models.CharField(blank=True, max_length=10, verbose_name='المحور - يسرى')),
                ('left_add', models.CharField(blank=True, max_length=10, verbose_name='القراءة - يسرى')),
                ('left_pd', models.CharField(blank=True, max_length=10, verbose_name='المسافة البؤرية - يسرى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الفحص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فحص نظر',
                'verbose_name_plural': 'فحوصات النظر',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('whatsapp', 'واتساب'), ('sms', 'SMS'), ('email', 'بريد إلكتروني')], max_length=20, verbose_name='نوع الإشعار')),
                ('message_type', models.CharField(choices=[('exam', 'إرسال الفحص الطبي'), ('delivery', 'طلب تسليم أو توصيل'), ('pickup', 'إشعار استلام النظارة'), ('invoice', 'فاتورة المشتريات'), ('confirmation', 'تأكيد الطلب'), ('reminder', 'تذكير بموعد الفحص')], max_length=20, verbose_name='نوع الرسالة')),
                ('message', models.TextField(blank=True, verbose_name='محتوى الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-sent_at'],
            },
        ),
    ]
