# Generated by Django 6.0 on 2026-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='البيانات')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
            ],
            options={
                'verbose_name': 'سجل Webhook',
                'verbose_name_plural': 'سجلات Webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='معرف رسالة واتساب')),
                ('direction', models.CharField(choices=[('outbound', 'صادر'), ('inbound', 'وارد')], max_length=10, verbose_name='الاتجاه')),
                ('recipient_phone', models.CharField(db_index=True, max_length=20, verbose_name='رقم المستلم')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('template', 'قالب'), ('image', 'صورة'), ('document', 'مستند')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('body', models.TextField(blank=True, verbose_name='محتوى الرسالة')),
                ('template_name', models.CharField(blank=True, max_length=255, verbose_name='اسم القالب')),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('read', 'تمت القراءة'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='البيانات الخام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل واتساب',
                'ordering': ['-created_at'],
            },
        ),
    ]
