# Generated by Django 6.0 on 2025-12-20 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-order_date'], 'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'عنصر فاتورة', 'verbose_name_plural': 'عناصر الفواتير'},
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='أضيف بواسطة'),
        ),
        migrations.AddField(
            model_name='sale',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='stock.laboratory', verbose_name='المعمل'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الخدمة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('transfer', 'تحويل بنكي'), ('mada', 'مدى'), ('later', 'آجل')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='رقم المعاملة أو الإيصال', max_length=100, verbose_name='المرجع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('transfer', 'تحويل بنكي'), ('mada', 'مدى'), ('later', 'آجل')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('created', 'تم الإنشاء'), ('lab', 'في المعمل'), ('ready', 'جاهز للاستلام'), ('received', 'تم الاستلام'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='created', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الضريبة (15%)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='الفاتورة'),
        ),
    ]
