# Generated by Django 6.0 on 2025-12-26 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50, unique=True, verbose_name='رمز الخدمة')),
                ('service_name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='تكلفة الخدمة (اختياري)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التكلفة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['service_name'],
            },
        ),
    ]
