# Generated by Django 6.0 on 2026-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='arrival_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إشعار وصول النظارة'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_choice',
            field=models.CharField(blank=True, choices=[('pickup', 'استلام من المحل'), ('delivery', 'توصيل')], max_length=10, verbose_name='طريقة الاستلام'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_choice_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ رد العميل على الاستلام'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الفاتورة عبر واتساب'),
        ),
    ]
